# Generated by Django 4.2.10 on 2024-02-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scouter', models.CharField(max_length=30)),
                ('match_number', models.CharField(max_length=30)),
                ('robot', models.CharField(choices=[('Red 1', 'Red 1'), ('Red 2', 'Red 2'), ('Red 3', 'Red 3'), ('Blue 1', 'Blue 1'), ('Blue 2', 'Blue 2'), ('Blue 3', 'Blue 3')], max_length=10)),
                ('team_number', models.IntegerField()),
                ('hp_at_amp', models.BooleanField()),
                ('mobile', models.BooleanField()),
                ('auto_amp_scored', models.IntegerField()),
                ('auto_amp_missed', models.IntegerField()),
                ('auto_speaker_scored', models.IntegerField()),
                ('auto_speaker_missed', models.IntegerField()),
                ('auto_foul', models.IntegerField()),
                ('coopertition', models.BooleanField()),
                ('teleop_amp_scored', models.IntegerField()),
                ('teleop_amp_missed', models.IntegerField()),
                ('teleop_speaker_scored', models.IntegerField()),
                ('teleop_speaker_missed', models.IntegerField()),
                ('teleop_trap', models.IntegerField()),
                ('teleop_foul', models.IntegerField()),
                ('end_position', models.CharField(choices=[('无爬升', 'No Climb'), ('爬升失败', 'Failed Climb'), ('停车', 'Parked'), ('Stage', 'Stage'), ('Spotlight', 'Spotlight')], max_length=10)),
                ('harmony', models.CharField(choices=[('无', 'Not Complete'), ('1 链', 'First On Chain'), ('2 链', 'Second On Chain'), ('3 链', 'Third On Chain')], max_length=10)),
                ('offense_skill', models.CharField(choices=[('不佳', 'Not Effective'), ('平均水平', 'Average'), ('非常有效', 'Very Effective'), ('未观测', 'Not Observed')], max_length=10)),
                ('defense_skill', models.CharField(choices=[('不佳', 'Not Effective'), ('平均水平', 'Average'), ('非常有效', 'Very Effective'), ('未观测', 'Not Observed')], max_length=10)),
                ('died', models.BooleanField()),
                ('tipped_over', models.BooleanField()),
                ('card', models.CharField(choices=[('无', 'No'), ('红牌', 'Red Card'), ('黄牌', 'Yellow Card')], max_length=10)),
                ('comments', models.TextField()),
            ],
        ),
    ]
