# Generated by Django 4.2.10 on 2024-02-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='no_show',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
