# Generated by Django 4.2.10 on 2024-02-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0002_record_no_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='driver_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='record',
            name='human_player_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='record',
            name='defense_skill',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='record',
            name='offense_skill',
            field=models.IntegerField(),
        ),
    ]
