# Generated by Django 4.2.10 on 2024-02-22 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0003_record_driver_rating_record_human_player_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='strategy_rating',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
