# Generated by Django 4.2.10 on 2024-02-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0005_record_cycle_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='PitTeam',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('team_number', models.CharField()),
                ('can_amp', models.BooleanField()),
                ('can_speaker', models.BooleanField()),
                ('can_trap', models.BooleanField()),
                ('chassis_type', models.CharField(max_length=30)),
                ('cycle_time', models.CharField(max_length=30)),
                ('auto_type', models.CharField(max_length=30)),
            ],
        ),
    ]
