# Generated by Django 4.2.10 on 2024-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0006_pitteam'),
    ]

    operations = [
        migrations.AddField(
            model_name='pitteam',
            name='picture_url',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
    ]
