# Generated by Django 4.2.10 on 2024-02-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scouting', '0007_pitteam_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pitteam',
            name='team_number',
            field=models.CharField(unique=True),
        ),
    ]
